## 1
name: Test and deploy

## Actions that will be executed when you push code currently none
on:
  push:

## 2
jobs:
  ## 3
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Unit tests
        run: ./gradlew testadd
        continue-on-error: true # IMPORTANT: allow pipeline to continue to Android Test Report step

      - name: Android Test Report
        uses: doanpt/AndroidTestReportAction@v1.5-alpha
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
  ## 4
  android_tests:
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest
        continue-on-error: true # IMPORTANT: allow pipeline to continue to Android Test Report step
        
      - name: Upload Test Reports Folder
        uses: actions/upload-artifact@v2
        if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
        with:
          name: reports
          path: app/build/reports/androidTests/connected/ # path to where the xml test results are stored

  ##5
  report:
    runs-on: [ ubuntu-latest ]
    needs: android_tests # The report job will run after test job
    if: ${{ always() }} # IMPORTANT: Execute report job regardless of status
    steps:
      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: reports
      - name: Android  Report Action
        uses: doanpt/AndroidTestReportAction@v1.5-alpha
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
